AWSTemplateFormatVersion: '2010-09-09'
Description: SES configs for email rules setup
Parameters:
  ConfigSetName:
    Type: String
  DomainRuleSetName:
    Type: String
  DomainName:
    Type: String

Resources:

  EmailsS3Bucket:
    Type: AWS::S3::Bucket

  EmailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EmailsS3Bucket
      PolicyDocument:
        Statement:
          -
            Action:
              - "s3:PutObject"
            Effect: "Allow"
            Resource: !Join ['', ['arn:aws:s3:::', !Ref EmailsS3Bucket, '/*' ]]
            Principal:
              Service: [ses.amazonaws.com]
            Condition:
              StringEquals:
                aws:Referer: !Ref 'AWS::AccountId'


  ConfigSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: !Ref ConfigSetName

  ReceiptRuleSet:
    Type: AWS::SES::ReceiptRuleSet
    Properties:
      RuleSetName: !Ref DomainRuleSetName

  ReceiptRule1:
    Type: AWS::SES::ReceiptRule
    Properties:
      Rule:
        Actions:
          - 
           S3Action:
            BucketName: !Ref EmailsS3Bucket
        Enabled: True
        Name: "ForwardAll"
        ScanEnabled: False
        Recipients:
          - !Join [ '@', [ 'test123', !Ref DomainName ] ]
      RuleSetName: !Ref DomainRuleSetName
  
